### ISSUE TITLE
day-night temperature color

### ISSUE THREAD

**Issue by neuromagus** [mrcnski/nimbus-theme#34]
It's me again.
Just read this, guys: 
https://justgetflux.com/research.html
https://iristech.co/what-is-the-best-color-temperature/

and utility:
https://www.debugpoint.com/2020/10/adjust-color-temperature-ubuntu-terminal/
http://jonls.dk/redshift/

Well, maybe need create "nimbus-night-theme" for 3k-2k temperature (and remove blue color, other colors changed too)?
And nimbus-day-theme for 5k(6500k) temperature?
Nimbus for day, nimbus for night?   

Thinking about this. Thanks.

**Comment by m-cat** [comment]
Thanks for the suggestion. If anyone wants to expand `nimbus` into more themes, feel free to submit PRs or start your own fork with the same colors.
